title: Control Theory Docs
remote_theme: just-the-docs/just-the-docs

# Optional: enable search
search_enabled: true

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

just_the_docs:
  includes:
    head: 
    - mathjax.html
